{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.0"
    }
  },
  "component" : {
    "group" : "com.github.skiddermc",
    "module" : "ForgeGradle",
    "version" : "f2c5bb338e",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "ForgeGradle-f2c5bb338e.jar",
      "url" : "ForgeGradle-f2c5bb338e.jar",
      "size" : 14561493,
      "sha512" : "90a830786ee888cc6bd53ed798401b7e09fdfbfadde2f325bebb6700ebe740ae7afd54e2415f7ffc0bfa93c2001c8cdb6881de9e70cc70fc77100ebd9b46026a",
      "sha256" : "8408ae5bf7ba950be33c4c8adf6da4f6b31e93881b65c22e3fcaac2be5a02db8",
      "sha1" : "ca37f80f83730efdad626de4fe874e09c1911cd1",
      "md5" : "48caa12abfd1b494c378cfa6e0097b08"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "org.ow2.asm",
      "module" : "asm-debug-all",
      "version" : {
        "requires" : "5.0.3"
      }
    }, {
      "group" : "com.google.guava",
      "module" : "guava",
      "version" : {
        "requires" : "18.0"
      }
    }, {
      "group" : "net.sf.opencsv",
      "module" : "opencsv",
      "version" : {
        "requires" : "2.3"
      }
    }, {
      "group" : "com.cloudbees",
      "module" : "diff4j",
      "version" : {
        "requires" : "1.1"
      }
    }, {
      "group" : "com.github.abrarsyed.jastyle",
      "module" : "jAstyle",
      "version" : {
        "requires" : "1.3"
      }
    }, {
      "group" : "net.sf.trove4j",
      "module" : "trove4j",
      "version" : {
        "requires" : "2.1.0"
      }
    }, {
      "group" : "com.github.jponge",
      "module" : "lzma-java",
      "version" : {
        "requires" : "1.3"
      }
    }, {
      "group" : "com.nothome",
      "module" : "javaxdelta",
      "version" : {
        "requires" : "2.0.1"
      }
    }, {
      "group" : "com.google.code.gson",
      "module" : "gson",
      "version" : {
        "requires" : "2.2.4"
      }
    }, {
      "group" : "com.github.tony19",
      "module" : "named-regexp",
      "version" : {
        "requires" : "0.2.3"
      }
    }, {
      "group" : "net.minecraftforge",
      "module" : "fernflower",
      "version" : {
        "requires" : "2.0-SNAPSHOT"
      }
    }, {
      "group" : "org.apache.httpcomponents",
      "module" : "httpclient",
      "version" : {
        "requires" : "4.3.3"
      }
    }, {
      "group" : "org.apache.httpcomponents",
      "module" : "httpmime",
      "version" : {
        "requires" : "4.3.3"
      }
    } ],
    "files" : [ {
      "name" : "ForgeGradle-f2c5bb338e.jar",
      "url" : "ForgeGradle-f2c5bb338e.jar",
      "size" : 14561493,
      "sha512" : "90a830786ee888cc6bd53ed798401b7e09fdfbfadde2f325bebb6700ebe740ae7afd54e2415f7ffc0bfa93c2001c8cdb6881de9e70cc70fc77100ebd9b46026a",
      "sha256" : "8408ae5bf7ba950be33c4c8adf6da4f6b31e93881b65c22e3fcaac2be5a02db8",
      "sha1" : "ca37f80f83730efdad626de4fe874e09c1911cd1",
      "md5" : "48caa12abfd1b494c378cfa6e0097b08"
    } ]
  } ]
}